import pandas as pd
desc = ['Numerical GPA',
 '1 - Female, 2 - Male',
 'Percep. of breakfast: 1 - Cereal, 2 - Donut',
 'Guessing calories in chicken piadina',
 'Importance of consuming calories per day: 1 - I dont know, 2 - Not important, 3 - Moderately important, 4 - Very important',
 'Guessing calories in a scone from Starbucks',
 'Percep. of coffee: 1 - Frappuccino, 2 - Espresso',
 'List 3-5 comfort foods that come to mind.',
 'What are some of the reasons that you eat comfort food?',
 'Comfort food reasons coded: 1 - Stress, 2 - Boredom, 3 - Depression/sadness, 4 - Hunger, 5 - Laziness, 6 - Cold weather, 7 - Happiness, 8 - Watching TV, 9 - None',
 'How often do you cook?: 1 - Every day, 2 - A couple of times a week, 3 - Whenever I can, but that is not very often, 4 - I help a little during holidays, 5 - Never',
 'Comfort food reasons coded 1',
 'What type of cuisine did you eat growing up?: 1 - American, 2 - Mexican/Spanish, 3 - Korean/Asian, 4 - Indian, 5 - American inspired international dishes, 6 - Other',
 'Describe your current diet',
 'Current diet coded: 1 - Healthy/balances/moderated, 2 - Unhealthy/cheap/too much/random, 3 - Same thing over and over, 4 - Unclear',
 'Percep. of drink: 1 - Orange juice, 2 - Soda',
  'Describe your eating changes since you got into college?',
 'College eating changes coded: 1 - Worse, 2 - Better, 3 - The same, 4 - Unclear',
 'College eating changes coded part 2: 1 – eat faster 2 – bigger quantity 3 – worse quality  4 – same food 5 – healthier 6 – unclear 7 – drink coffee  8 – less food 9 – more sweets 10 – timing  11 – more carbs or snacking 12 – drink more water 13 – more variety',
 'frequency of eating out in a typical week  1 - Never  2 - 1-2 times  3 - 2-3 times  4 - 3-5 times  5 - every day',
 'do you work?  1 - yes full time  2 - yes part time  3 – no 4 - other',
 'How likely to eat ethnic food  1 - very unlikely  2 - unlikely  3 - neutral  4 - likely  5 - very likely',
 'how often do you exercise in a regular week? 1 - Everyday  2 - Twice or three times per week  3 - Once a week 4 - Sometimes  5 – Never',
 'Father education –  1 - less than high school  2 - high school degree  3 - some college degree  4 - college degree  5 - graduate degree',
 'Father profession',
 'What is your favorite cuisine?',
 "Favorite cuisine coded: 0-none 1 – Italian/French/greek 2 – Spanish/mexican 3 – Arabic/Turkish 4 – asian/chineses/thai/nepal 5 – American 6 – African  7 – Jamaican 8 – indian", 
 'was your favorite food cooked at home or store bought?  1 - cooked at home  2 - store bought  3 - both bought at store and cooked at home',
 'What was your favorite childhood food?',
 'Percep. of fries: 1 - McDonalds Fries, 2 - Homemade Fries',
 'How likely to eat fruit in a regular day  1 - very unlikely  2 - unlikely  3 - neutral  4 - likely  5 - very likely',
 'Grade level:  1 - freshman  2 -Sophomore  3 - Junior  4 - Senior',
 'How likely to eat greek food when available? 1 - very unlikely  2 - unlikely  3 - neutral  4 - likely  5 - very likely',
 'How likely are you to agree with the following statement: “I feel very healthy!” ? 1 to 10 where 1 is strongly agree and 10 is strongly disagree',
 'What is a healthy meal to you?',
 'Describe your ideal diet',
 'Ideal diet coded:  1 – portion control 2 – adding veggies/eating healthier food/adding fruit	 3 – balance 4 – less sugar 5 – home cooked/organic 6 – current diet 7 – more protein 8 – unclear',
 'income 1 - less than $15,000  2 - $15,001 to $30,000  3 - $30,001 to $50,000  4 - $50,001 to $70,000  5 - $70,001 to $100,000  6 - higher than $100,000',
 'how likely are you to eat indian food when available 1 - very unlikely  2 - unlikely  3 - neutral  4 - likely  5 - very likely',
 'how likely are you to eat Italian food when available?  1 - very unlikely  2 - unlikely  3 - neutral  4 - likely  5 - very likely',
 'how likely are you to agree with the following statement: “I feel life is very rewarding!” ? 1 to 10 where 1 is strongly agree and 10 is strongly disagree',
 'Marital status: 1 -Single  2 - In a relationship  3 - Cohabiting  4 - Married  5 - Divorced  6 - Widowed',
 'What would you serve to a friend for dinner?',
 'Mother education –  1 - less than high school  2 - high school degree  3 - some college degree  4 - college degree  5 - graduate degree',
 'What is your mothers profession?',
 'How often do you check the nutritional facts on a product?:  1 - never  2 - on certain products only  3 - very rarely  4 - on most products  5 - on everything',
 'living situation 1 - On campus  2 - Rent out of campus  3 - Live with my parents and commute  4 - Own my own house',
 'Approximately how many days a week did your parents cook?  1 - Almost everyday  2 - 2-3 times a week  3 - 1-2 times a week  4 - on holidays only  5 - never',
 'How much would you pay for meal out?  1 - up to $5.00  2 - $5.01 to $10.00  3 - $10.01 to $20.00  4 - $20.01 to $30.00  5 - $30.01 to $40.00  6 - more than $40.01',
 'How likely to eat persian food when available? 1 - very unlikely  2 - unlikely  3 - neutral  4 - likely  5 - very likely',
 'self perception of weight  6 - i dont think myself in these terms  5 - overweight  4 - slightly overweight  3 - just right  2 - very fit  1 - slim',
 'Percep. of soup: 1 - Veggie soup, 2 - Creamy soup',
 'do you do any sporting activity?   1 - Yes  2 - No 99 - No answer',
 'How likely to eat thai food when available? 1 - very unlikely  2 - unlikely  3 - neutral  4 - likely  5 - very likely',
 'Guessing calories in a Chipotle burrito',
 'Guessing calories in a Panera Bread Roasted Turkey and Avocado BLT',
 'What type of sports do you do?',
 'How likely to eat veggies in a day?  1 - very unlikely  2 - unlikely  3 - neutral  4- likely  5 - very likely',
 'do you take any supplements or vitamins? 1 – yes 2 – no',
 'Guessing calories in a waffle potato sandwich',
 'Weight in pounds']

cols = pd.read_csv('food_dataset.csv').columns.values
column_desc = pd.DataFrame(columns=['Column', 'Description'])
column_desc['Column'] = cols
column_desc['Description'] =  desc

def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn